name: blucon_multi_platform
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_blue_plus: ^1.31.16
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/mode_one_heart.png
    - assets/images/mode_two_hearts.png
    - assets/images/mode_three_hearts.png
    - assets/images/mode_posture0.png
    - assets/images/mode_posture1.png
    - assets/images/mode_posture2.png
    - assets/images/mode_posture3.png
    - assets/images/mode_posture4.png
    - assets/images/mode_posture5.png
    - assets/images/mode_posture6.png
    - assets/images/mode_stop.png